import jsPDF from "jspdf";

export const generateRentAgreementPdf = ({ property, agreement, role }) => {
  if (!property || !agreement) return;

  const doc = new jsPDF();

  const startDate = agreement.startDate
    ? new Date(agreement.startDate)
    : null;
  const endDate = agreement.endDate ? new Date(agreement.endDate) : null;

  const formatDate = (date) =>
    date
      ? date.toLocaleDateString("en-IN", {
          year: "numeric",
          month: "short",
          day: "numeric",
        })
      : "N/A";

  const monthlyRent = agreement.monthlyRent || 0;
  const securityDeposit = agreement.securityDeposit || 0;
  const maintenance = agreement.maintenance || 0;

  doc.setFontSize(18);
  doc.setTextColor(33, 37, 41);
  doc.text("Residential Rent Agreement", 105, 18, { align: "center" });

  doc.setFontSize(11);
  doc.setTextColor(100, 116, 139);
  doc.text("Generated by Real Estate Management Platform", 105, 26, {
    align: "center",
  });

  doc.setDrawColor(229, 231, 235);
  doc.line(15, 32, 195, 32);

  doc.setTextColor(15, 23, 42);
  doc.setFontSize(12);
  doc.text("Property Details", 15, 40);

  doc.setFontSize(10);
  doc.text(`Title: ${property.title || "N/A"}`, 15, 48);
  doc.text(`Location: ${property.location || "N/A"}`, 15, 54);
  doc.text(`Listed Price: ${property.price || "N/A"}`, 15, 60);

  const tenantName =
    role === "tenant"
      ? agreement.buyerName || "Tenant"
      : property.tenantName || "Tenant";
  const tenantEmail =
    role === "tenant"
      ? agreement.buyerEmail || ""
      : property.tenantEmail || "";
  const tenantPhone =
    role === "tenant" ? agreement.buyerPhone || "" : "";

  const landlordName =
    role === "tenant"
      ? property.landlordName || "Property Owner"
      : agreement.sellerName || "Property Owner";
  const landlordEmail =
    role === "tenant" ? property.landlordEmail || "" : "";
  const landlordPhone = agreement.sellerPhone || "";

  doc.setFontSize(12);
  doc.text("Parties", 15, 72);
  doc.setFontSize(10);
  doc.text("Landlord", 15, 80);
  doc.text(`Name: ${landlordName}`, 15, 86);
  if (landlordEmail) doc.text(`Email: ${landlordEmail}`, 15, 92);
  if (landlordPhone) doc.text(`Phone: ${landlordPhone}`, 15, 98);

  doc.text("Tenant", 105, 80);
  doc.text(`Name: ${tenantName}`, 105, 86);
  if (tenantEmail) doc.text(`Email: ${tenantEmail}`, 105, 92);
  if (tenantPhone) doc.text(`Phone: ${tenantPhone}`, 105, 98);

  doc.setFontSize(12);
  doc.text("Agreement Terms", 15, 112);
  doc.setFontSize(10);
  doc.text(`Start Date: ${formatDate(startDate)}`, 15, 120);
  doc.text(`End Date: ${formatDate(endDate)}`, 15, 126);
  doc.text(`Monthly Rent: ₹${monthlyRent.toLocaleString("en-IN")}`, 15, 132);
  doc.text(
    `Security Deposit: ₹${securityDeposit.toLocaleString("en-IN")}`,
    15,
    138
  );
  doc.text(
    `Maintenance: ₹${maintenance.toLocaleString("en-IN")}`,
    15,
    144
  );

  doc.setFontSize(11);
  doc.text("Key Clauses", 15, 160);
  doc.setFontSize(9);
  const clauses = [
    "1. The tenant shall pay the monthly rent on or before the agreed due date each month.",
    "2. The rent agreement is non-cancellable by the tenant until the end date of the lease period.",
    "3. The owner may terminate the agreement earlier only under exceptional circumstances and subject to applicable laws.",
    "4. The tenant shall use the premises for residential purposes only and maintain the property in good condition.",
    "5. Any disputes arising out of this agreement will be handled as per the platform policies and applicable law.",
  ];

  let y = 168;
  clauses.forEach((line) => {
    doc.text(line, 15, y, { maxWidth: 180 });
    y += 6;
  });

  const footerY = 260;
  doc.setFontSize(11);
  doc.text("Signatures", 15, footerY);
  doc.setFontSize(10);
  doc.text("Landlord Signature: ______________________", 15, footerY + 10);
  doc.text("Tenant Signature: ______________________", 105, footerY + 10);

  doc.setFontSize(8);
  doc.setTextColor(107, 114, 128);
  doc.text(
    "This is a computer-generated agreement PDF.",
    105,
    290,
    {
      align: "center",
    }
  );

  const fileName = `Rent-Agreement-${
    property.title ? property.title.substring(0, 24) : "Property"
  }.pdf`;
  doc.save(fileName.replace(/\s+/g, "-"));
};
